/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ys_ffmpeg_ffmpegsimple_util_FFmpegUtil */

#ifndef _Included_com_ys_ffmpeg_ffmpegsimple_util_FFmpegUtil
#define _Included_com_ys_ffmpeg_ffmpegsimple_util_FFmpegUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ys_ffmpeg_ffmpegsimple_util_FFmpegUtil
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_com_ys_ffmpeg_ffmpegsimple_util_FFmpegUtil_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
